baseURL = 'https://fgabel.github.io/'
languageCode = 'en-us'
title = 'Frank Gabel, PhD'

# Disable taxonomy pages since this is a personal site
disableKinds = ['taxonomy', 'taxonomyTerm']

[params]
  # Set color theme to auto (switches between light/dark based on system preference)
  BookTheme = 'auto'
  
  # Disable table of contents by default
  BookToC = false
  
  # Disable search
  BookSearch = false
  
  # Disable comments
  BookComments = false
  
  # Show all sections in menu
  BookSection = '*'
  
  # Repository information
  BookRepo = 'https://github.com/fgabel/fgabel.github.io'

# Enable menu rendering from front matter weight
[menu]
  [[menu.before]]
    name = "Home"
    url = "/"
    weight = 1
  
  [[menu.before]]
    name = "About"
    url = "/about"
    weight = 2
  
  [[menu.before]]
    name = "Blog"
    url = "/posts"
    weight = 3
  
  [[menu.before]]
    name = "Links"
    url = "/links"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true

